### ISSUE TITLE
Issues with History and Setting button functionality on iPhone 11 Pro ios 15.3.1

### ISSUE THREAD

**Issue by Bristopher** [georapbox/barcode-scanner#19]
## Expected Behavior
Same functionality as an iPhone on a newer ios

## Actual Behavior
History button refreshes the whole page and doesn't open, and setting button does nothing, they also seem to be misaligned (the history button isn't where the button functionality is, see picture 2). It also seems the cameraResults outline is incorrectly displaying (see picture 1). 

I used Browerstack to verify this wasn't just my issue, and ios 15.6+(iphone 13 Pro) works as intended but 14.4(iPhone 12 Pro, closest to before my version) also has the same issues if not more. Considering this version of ios isn't _too_ old I'm not sure what is causing this, any insight would be helpful because I'm sure support for older versions isn't necessarily a priority. (great project btw!)

<img src="https://github.com/user-attachments/assets/1c5361eb-8785-4301-9190-4014247bbd90" width="300">
  
<img src="https://github.com/user-attachments/assets/ab085e8f-b436-48af-b1b4-2cb089da7498" width="300">

## Specifications

  - Version: 15.3.1
  - Platform: iPhone 11 Pro Safari, Chrome

**Comment by georapbox** [comment]
Hi,

I think that the issue is due to the usage of the native <dialog> element that is supported on Safari and iOS 15.4 and after. See [browser compatibility](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog#browser_compatibility).

The dialog element is used on all 3 cases that you have issues. The history and settings buttons trigger a dialog to open and similarly the scanned results are displayed inside a dialog element only this time it is not opened as a modal but inline.

As an easy fix, I could probably check for dialog support and possibly hide the history and settings buttons altogether and maybe refactor the results to not use the dialog element but just a regular div element to render into. This way, at least the basic functionality would work on older browsers that do not support the dialog element while the secondary functionality of history will not be available.

**Comment by Bristopher** [comment]
Ahhh I see, the secondary functionality of history not working is fine, I just want the settings to work so I can enable beep/vibrate. Thanks!

**Comment by georapbox** [comment]
To be honest, I consider both history and settings as secondary functionality. The settings are just some nice to have features that do not affect the core functionality. After all [navigator.vibrate()](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/vibrate#browser_compatibility) is not supported in iOS at all and the beeb sound also seems to not work in iOS, at least on latest iPadOS 17.3.1.

Therefore, because those features are not critical for the app's critical functionality, I would suggest that I wouldn't start considering adding third party dialog plugins just for secondary functionality to work. I consider it as graceful degradation to not support those features on older devices or OS versions.

But for the critical functionality, such as the scan results, i will be changing the way it works now, to achieve greater support.

**Comment by Bristopher** [comment]
If vibrate and beep aren't supported on IOS at all then darn yeah nevermind, just changing scan results to have better support is perfect thanks!

**Comment by georapbox** [comment]
Hi,

In the latest deployment I've hidden the history and settings buttons and dialogs if native `<dialog>` element is not supported and refactored the scanned results to not render a dialog element for greater compatibility. Here's the related [PR](https://github.com/georapbox/barcode-scanner/pull/20), I've made some more accessibility improvements along the way. Could you please test if this is working as expected? Thanks!

**Comment by Bristopher** [comment]
Looks clean, just tested it. Great work, thanks!
