### ISSUE TITLE
About Barcode-scanner app Scanner section not scanning properly and giving garbage value

### ISSUE THREAD

**Issue by Kunwar-Abhishek-Singh** [georapbox/barcode-scanner#9]
I will sincerely have to make you know that, when i started using your app then i noticed one thing that, at the time of using barcode scanner app with scanning module then the scanner selected self the wide angle camera module instead of selecting the primary camera and due to this it scans but the image got appeared bit blurry. So could you plzz fix this issue by switching the camera to Primary camera instead of wide angle lens....

**Comment by IProxymate** [comment]
@georapbox Hi! Is there any way to manually select the camera I need? In some browsers, I get a blurry image, so it doesn't scan barcodes. My guess is that the app is choosing the wide-lens camera.

P.S.: I found some posts about this problem on StackOverflow, but I can't figure out how to modify your code, because I can't find the getUserMedia() method.

**Comment by Kunwar-Abhishek-Singh** [comment]
Thanks for the reply.
I will wait for the fixation of the error.

**Comment by georapbox** [comment]
Hi, 

I've made an experimental deployment under https://georapbox.github.io/barcode-scanner/?experimental to test selection of the available video input devices. Under the hood it uses [MediaDevices.enumerateDevices()](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices) to enumerated the available video input devices and if there more than one a <select> element lists the available devices to choose from.

Could you please test if this solution is working for you? I've tested on a a few different Android devices and on an iPad and it seems to be working but unfortunately I don't have any device with a wide-lens camera to test.

If this solution works and in the available devices are also listed the back and front cameras, then it might be safe to assume that the button with the camera icon on bottom of the video stream is no longer necessary.

**Comment by IProxymate** [comment]
Hi, 

Tested on Galaxy Fold 4. Solution is working! 
Thank you

**Comment by georapbox** [comment]
Does it also display the front and back cameras appropriately? Asking in order to see if I can get rid of the camera icon button on bottom and place the camera select element in its place.

**Comment by IProxymate** [comment]
Both the front and back cameras are working as expected. However, the camera icon stops working properly if we choose a non-default camera. So, it might be better to remove the icon altogether, or as an alternative, we can open a modal window with camera selection when clicking on the camera icon instead of the current dropdown menu.

**Comment by georapbox** [comment]
Yes, I know... I removed the experimental flag and the camera icon and added the dropdown in its place. I might reconsider the UI at a later point but for the time it seems to be working just fine.

**Comment by georapbox** [comment]
Fixed by
- https://github.com/georapbox/barcode-scanner/pull/22
- https://github.com/georapbox/barcode-scanner/pull/23
